all:

local_sudo_deploy:
	MIX_ENV=prod mix release --no-tar
	sudo -u link_off rsync --delete -rt --exclude 'var/' \
		_build/prod/rel/link_off/ \
		/home/link_off/app/link_off/
	sudo -u link_off /home/link_off/app/link_off/bin/link_off deploy_restart

remote_ssh_deploy:
	MIX_ENV=prod mix release --no-tar
	rsync --delete -rt --exclude 'var/' \
		_build/prod/rel/link_off/ \
		link_off@SOME-HOST:app/link_off/
	ssh link_off@SOME-HOST app/link_off/bin/link_off deploy_restart
